---
driver:
  name: 'docker'
  memory: '512m'
  cpu: 2
  use_sudo: false
  privileged: <%= ENV['TRAVIS'] ? false : true %>
  add_host: <%= ENV['TRAVIS'] ? [] : [['localhost.localdomain', '127.0.0.1']] %>
provisioner:
  name: 'chef_solo'
  require_chef_omnibus: false
  chef_omnibus_root: '/opt/chef'
  attributes:
    kafka:
      uid: 1234
      gid: 5678
      version: <%= ENV.fetch('KAFKA_VERSION', '1.0.0').inspect %>
      scala_version: <%= ENV.fetch('SCALA_VERSION', '2.11').inspect %>
      checksum: <%= ENV.fetch('KAFKA_CHECKSUM', '').inspect %>
      md5_checksum: <%= ENV.fetch('KAFKA_MD5', '').inspect %>
      sha512_checksum: <%= ENV.fetch('KAFKA_SHA512', '').inspect %>
      heap_opts: '-Xmx256M -Xms256M'
      ulimit_file: 128000
      broker:
        broker.id: 1
        controlled.shutdown.enable: <%= ENV.fetch('KAFKA_CTRL_SHUTDOWN', false) %>
        log.dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
        zookeeper.connect: ['localhost:2181']
      log4j:
        appenders:
          zookeeperAppender:
            type: 'org.apache.log4j.FileAppender'
            file: '/var/log/kafka/zookeeper.log'
            layout:
              type: 'org.apache.log4j.PatternLayout'
              conversion_pattern: '[%d] %p %m (%c)%n'
        loggers:
          org.apache.zookeeper:
            level: 'INFO'
            appender: 'zookeeperAppender'
            additivity: false
platforms:
  - name: centos-6
    driver_config:
      provision_command:
        - yum install -y tar java-1.8.0-openjdk-headless
        - curl -L https://chef.io/chef/install.sh | bash -s -- -v <%= ENV.fetch('CHEF_VERSION', '12') %> -c <%= ENV.fetch('CHEF_CHANNEL', 'stable') %>
  - name: debian-7
    driver_config:
      provision_command:
        - apt-get install -y default-jre-headless net-tools --no-install-recommends
        - curl -L https://chef.io/chef/install.sh | bash -s -- -v <%= ENV.fetch('CHEF_VERSION', '12') %> -c <%= ENV.fetch('CHEF_CHANNEL', 'stable') %>
  - name: ubuntu-14.04
    driver_config:
      provision_command:
        - apt-get install -y default-jre-headless --no-install-recommends
        - curl -L https://chef.io/chef/install.sh | bash -s -- -v <%= ENV.fetch('CHEF_VERSION', '12') %> -c <%= ENV.fetch('CHEF_CHANNEL', 'stable') %>
suites:
  - name: default
    run_list:
      - recipe[kafka]
    attributes:
      kafka:
        init_style: false
  - name: sysv
    run_list:
      - recipe[kafka]
    attributes:
      kafka:
        init_style: 'sysv'
  - name: runit
    driver_config:
      run_command: /sbin/init
    run_list:
      - recipe[runit]
      - recipe[kafka]
    excludes:
      - ubuntu-14.04
    attributes:
      kafka:
        init_style: 'runit'
