---
driver:
  name: vagrant
  box_check_update: false
  customize:
    memory: 512
    cpus: 2
provisioner:
  name: 'chef_solo'
  require_chef_omnibus: <%= ENV.fetch('CHEF_VERSION', '12').inspect %>
  solo_rb:
    ssl_verify_mode: :verify_peer
  attributes:
    java:
      jdk_version: 7
    kafka:
      uid: 1234
      gid: 5678
      version: <%= ENV.fetch('KAFKA_VERSION', '1.0.0').inspect %>
      scala_version: <%= ENV.fetch('SCALA_VERSION', '2.11').inspect %>
      checksum: <%= ENV.fetch('KAFKA_CHECKSUM', '').inspect %>
      md5_checksum: <%= ENV.fetch('KAFKA_MD5', '').inspect %>
      sha512_checksum: <%= ENV.fetch('KAFKA_SHA512', '').inspect %>
      heap_opts: '-Xmx256M -Xms256M'
      ulimit_file: 128000
      broker:
        broker.id: 1
        controlled.shutdown.enable: <%= ENV.fetch('KAFKA_CTRL_SHUTDOWN', false) %>
        log.dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
        zookeeper.connect: ['localhost:2181']
      log4j:
        appenders:
          zookeeperAppender:
            type: 'org.apache.log4j.FileAppender'
            file: '/var/log/kafka/zookeeper.log'
            layout:
              type: 'org.apache.log4j.PatternLayout'
              conversion_pattern: '[%d] %p %m (%c)%n'
        loggers:
          org.apache.zookeeper:
            level: 'INFO'
            appender: 'zookeeperAppender'
            additivity: false
platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
    run_list:
      - recipe[apt]
  - name: debian-8.8
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: fedora-26
    attributes:
      java:
        jdk_version: 8
suites:
  - name: default
    run_list:
      - recipe[kafka]
    attributes:
      kafka:
        init_style: false
  - name: sysv
    run_list:
      - recipe[java]
      - recipe[kafka]
    includes:
      - centos-6.9
      - debian-7.11
  - name: upstart
    run_list:
      - recipe[java]
      - recipe[kafka]
    includes:
      - ubuntu-14.04
    attributes:
      kafka:
        init_style: 'upstart'
  - name: systemd
    run_list:
      - recipe[java]
      - recipe[kafka]
    includes:
      - centos-7.3
      - debian-8.8
      - fedora-26
    attributes:
      kafka:
        init_style: 'systemd'
  - name: runit
    run_list:
      - recipe[java]
      - recipe[runit]
      - recipe[kafka]
    excludes:
      - centos-7.3
      - fedora-26
    attributes:
      kafka:
        init_style: 'runit'
