language: ruby
sudo: required
services:
  - docker
cache:
  - bundler
rvm:
  - 2.3
env:
  global:
    - KITCHEN_YAML=.kitchen.docker.yml
  matrix:
    - CHEF_VERSION=12 KAFKA_VERSION=0.8.1.1 SCALA_VERSION=2.9.2 KAFKA_MD5=7541ed160f1b3aa1a5334d4e782ba4d3
    - CHEF_VERSION=12 KAFKA_VERSION=1.0.0 SCALA_VERSION=2.11 KAFKA_CTRL_SHUTDOWN=true
    - CHEF_VERSION=13 KAFKA_VERSION=1.0.0 SCALA_VERSION=2.11 KAFKA_SHA512=b698028485d460c494af942b2dfa41c7342a2ad6052b543c95289cd1e832a1ebcf679b7e568dcabc342c799765337b94f91bc0cf0ee915534cdf82d1635a622a
    - CHEF_VERSION=13 KAFKA_VERSION=1.0.0 SCALA_VERSION=2.11 CHEF_CHANNEL=current
install: travis_wait bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
script: bundle exec kitchen test --destroy=always
matrix:
  fast_finish: true
  allow_failures:
    - env: CHEF_VERSION=13 KAFKA_VERSION=1.0.0 SCALA_VERSION=2.11 CHEF_CHANNEL=current
  include:
    - sudo: false
      env: []
      rvm: 2.3
      script: bundle exec rake test
